# Create a window that shows the status of a set of LCC nodes
#
# The list is obtained from a NodeList.csv CSV file containing the node names.  This
# can be generated by the "Write CSV" button on the main LccPro screen.
#
# Bob Jacobsen 2026

import java
import javax
import jmri
import org.openlcb

global WatchNodesAndDisplayPanel
class WatchNodesAndDisplayPanel (javax.swing.JPanel) :
    
    def configure(self, name) :
        import java
        import javax
        
        self.icon = javax.swing.JLabel(javax.swing.ImageIcon("resources/icons/misc/Twiddle-yellow.gif"))
        self.label = javax.swing.JLabel(name)

        self.setLayout(java.awt.FlowLayout(java.awt.FlowLayout.LEFT))

        self.add(self.icon)
        self.add(self.label)
        
    def update(self, ok) :
        import javax
        if (ok) :
            self.icon.icon = javax.swing.ImageIcon("resources/icons/misc/Checkmark-green.gif")
        else :
            self.icon.icon = javax.swing.ImageIcon("resources/icons/misc/X-red.gif")
        

class WatchNodesAndDisplay (jmri.jmrit.automat.AbstractAutomaton) :
    import org.apache.commons.csv

    
    def init(self):
        import java
        import javax
        import jmri
        global WatchNodesAndDisplayPanel
        
        frame = jmri.util.JmriJFrame("LCC Node Status", True, True)
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE)
        frame.contentPane.setLayout(javax.swing.BoxLayout(frame.contentPane, javax.swing.BoxLayout.Y_AXIS))
        self.status = javax.swing.JLabel("Still scanning network")
        frame.contentPane.add(self.status)
        content = javax.swing.JPanel()
        content.setLayout(javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS))
        scrollPane = javax.swing.JScrollPane(content)
        frame.contentPane.add(scrollPane)
        
        inFile = java.io.File(jmri.util.FileUtil.getUserFilesPath() + 'NodeList.csv')
        csvFormat = org.apache.commons.csv.CSVFormat.Builder.create(org.apache.commons.csv.CSVFormat.DEFAULT).setHeader().setCommentMarker('#').build()
        csvFile = org.apache.commons.csv.CSVParser.parse(inFile, java.nio.charset.StandardCharsets.UTF_8, csvFormat)

        self.nodePanels = {}

        for record in csvFile.getRecords():
            nodeName = record.get("Name")
            if nodeName != "" :

                panel = WatchNodesAndDisplayPanel()

                panel.configure(nodeName)
                self.nodePanels[nodeName] = panel

                content.add(panel)
            
        csvFile.close()
        frame.setVisible(True)
    
    def handle(self) :
        import jmri
        import org.openlcb

        self.waitMsec(10000)

        # get node table
        olcbConfigMgr = jmri.InstanceManager.getDefault().getInstance(jmri.jmrix.openlcb.OlcbConfigurationManager)
        store = olcbConfigMgr.get(org.openlcb.MimicNodeStore)
        
        snipNodeNames = []
        for node in store.getNodeMemos() :
            snip = node.getSimpleNodeIdent()
            if (snip != None) :
                snipNodeNames.append(snip.getUserName())
        failures = 0
        
        for nodeName in self.nodePanels :
            present = nodeName in snipNodeNames
            panel = self.nodePanels[nodeName]
            panel.update(present)
            if not present : failures = failures + 1
           
        self.status.text = str(failures)+" nodes not found"         
        
        # and repeat
        return True

a = WatchNodesAndDisplay()
a.setName("WatchNodesAndDisplay")
a.start()
