#JMRI Preferences version 5.15.11+Re6f137d282
#Sat Jul 11 20:30:08 PDT 2026
apps-systemconsole.fontSize=12
apps-systemconsole.fontStyle=0
apps-systemconsole.scheme=0
apps-systemconsole.wrapStyle=2
jmri-configurexml.displayDialog=ShowDialog
jmri-configurexml.enableStoreCheck=false
jmri-configurexml.excludeFileHistory=false
jmri-configurexml.excludeFontExtensions=true
jmri-configurexml.excludeJmriVersion=true
jmri-configurexml.excludeMemoryContents=true
jmri-configurexml.excludeMemoryIMCURRENTTIME=true
jmri-configurexml.excludeMemoryTimebase=true
jmri-configurexml.ignoreSensorColors=true
jmri-configurexml.ignoreTimebase=true
jmri-configurexml.shortenLayoutEditorWrites=true
jmri-implementation.scripts=program\:jython/
jmri-implementation.user-files=profile\:
jmri-jmris-simpleserver.port=2048
jmri-jmris-srcp.port=4303
jmri-jmrit-consisttool.updateCV19=false
jmri-jmrit-logixng-implementation.errorHandlingType=ShowDialogBox
jmri-jmrit-logixng-implementation.ifThenElseExecuteTypeDefault=ExecuteOnChange
jmri-jmrit-logixng-implementation.installDebugger=true
jmri-jmrit-logixng-implementation.logAllAfter=false
jmri-jmrit-logixng-implementation.logAllBefore=false
jmri-jmrit-logixng-implementation.showSystemNameInExceptions=false
jmri-jmrit-logixng-implementation.showSystemUserNames=false
jmri-jmrit-logixng-implementation.startLogixNGOnStartup=true
jmri-jmrit-logixng-implementation.strictTypingGlobalVariables=false
jmri-jmrit-logixng-implementation.strictTypingLocalVariables=false
jmri-jmrit-logixng-implementation.treeEditorHighlightRow=false
jmri-jmrit-roster.defaultOwner=
jmri-jmrit-roster.directory=preference\:
jmri-jmrit-symbolicprog.canCacheDefault=false
jmri-jmrit-symbolicprog.disableProgrammingOnMain=false
jmri-jmrit-symbolicprog.disableProgrammingTrack=false
jmri-jmrit-symbolicprog.doConfirmRead=false
jmri-jmrit-symbolicprog.dontDetachPanes=false
jmri-jmrit-symbolicprog.showCvNumbers=false
jmri-jmrit-symbolicprog.showEmptyPanes=true
jmri-jmrix-loconet-loconetovertcp.port=1234
jmri-managers.allInternalDefaults=false
jmri-managers.defaults.jmri-AddressedProgrammerManager=LocoNet
jmri-managers.defaults.jmri-CommandStation=LocoNet
jmri-managers.defaults.jmri-ConsistManager=LocoNet
jmri-managers.defaults.jmri-GlobalProgrammerManager=LocoNet
jmri-managers.defaults.jmri-PowerManager=LocoNet
jmri-managers.defaults.jmri-ThrottleManager=LocoNet
jmri-server-json.heartbeatInterval=15000
jmri-server-json.port=2056
jmri-server-json.validateClientMessages=false
jmri-server-json.validateServerMessages=false
jmri-util-gui.editorUseOldLocSize=false
jmri-util-gui.fontSize=0
jmri-util-gui.graphicTableState=false
jmri-util-gui.jfilechooserformat=0
jmri-util-gui.locale=en
jmri-util-gui.lookAndFeel=javax.swing.plaf.metal.MetalLookAndFeel
jmri-util-gui.maxComboRows=0
jmri-util-gui.nonstandardMouseEvent=false
jmri-util-gui.oblockEditTabbed=false
jmri-util-gui.showToolTipDismissDelay=4000
jmri-util.openHelpOnFile=true
jmri-util.openHelpOnJMRIWebServer=false
jmri-util.openHelpOnline=false
jmri-web-server.allowRemoteConfig=false
jmri-web-server.clickDelay=1
jmri-web-server.disableFrames=true
jmri-web-server.disallowedFrames.0=DecoderPro
jmri-web-server.disallowedFrames.1=PanelPro
jmri-web-server.disallowedFrames.2=LocoNet Simulator
jmri-web-server.disallowedFrames.3=Preferences
jmri-web-server.disallowedFrames.4=WiThrottle
jmri-web-server.disallowedFrames.5=Change Signal Head Icons
jmri-web-server.disallowedFrames.6=Item Palette
jmri-web-server.port=12080
jmri-web-server.railroadName=PMRRM Dispatcher
jmri-web-server.readonlyPower=true
jmri-web-server.redirectFramesToPanels=true
jmri-web-server.refreshDelay=5
jmri-web-server.simple=false
jmri-web-server.useAjax=true
jmri-web-server.useZeroConf=true
profile.id=Dispatch_Work_in_Progress.3f79267a
profile.name=Dispatcher Work in Progress
